---
title: "DC Crime in 2018"
author: "Andrew Stephens"
output: html_notebook
---
#Read packages
```{r}
library(sf)
library(leaflet)
library(tmap)
library(tidyverse)
library(janitor)
library(readxl)
library(skimr)
library(summarytools)
library(ggplot2)
```

Import data
```{r}
df_crime <- read_excel("../data_raw/Crime_Incidents_in_2018.xlsx") %>% clean_names()
```

Select only the types of crime and the census tract
```{r}
df_crime2 <- df_crime %>% select(c(offense, census_tract))
```

Group by census tract then count the number of crimes per census tract
```{r}
df_crime3 <- df_crime2 %>% group_by(census_tract) %>%
  count(census_tract) %>%
  rename(totl = n)
```

Check to make sure that every crime incident is accounted for 
```{r}
df_crime3 %>% colSums()
```

Plot the data for visualization 
```{r}
df_crime3 %>% ggplot(aes(x=census_tract, y=totl )) +
  geom_point()
```

Read shapefile data


```{r}
census_sf =  st_read("../data_raw/tl_2019_11_tract/tl_2019_11_tract.shp") %>% clean_names()
```

```{r}
tmap_mode("view")
tm_shape(census_sf)+tm_polygons(alpha=.3)
```


Plot crime data on a map

```{r}
crime_sf = st_as_sf(df_crime, coords = c("x", "y"), 
                 crs = 4269, agr = "constant")
```

```{r}
tm_shape(crime_sf)+tm_dots(size=.02,alpha=.2,col="red")+
  tm_shape(census_sf)+tm_polygons(alpha=.3)+
  tm_basemap( leaflet::providers$OpenStreetMap )
```

Spacial join of crimes and census tract

```{r}
dfj=st_join(crime_sf,census_sf,join=st_within)

dfj2 =st_join(census_sf,crime_sf,join=st_contains) %>% count(name) 

dfj2 %>% tm_shape()  +tm_polygons("n",alpha=.6)+
  tm_basemap( leaflet::providers$OpenStreetMap )

```
